# Generated by Django 4.1 on 2022-10-01 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppBlog', '0004_alter_post_cuerpo'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='imagen_post',
            field=models.ImageField(blank=True, null=True, upload_to='imagenes/'),
        ),
    ]
